/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_TESTPROTOS_BIG_MESSAGE_PB_H_INCLUDED
#define PB_TESTPROTOS_BIG_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _testprotos_NPC { 
    pb_callback_t name;
    double health;
    pb_callback_t publicId;
} testprotos_NPC;

typedef struct _testprotos_PlayerResponse { 
    pb_callback_t publicId;
    pb_callback_t accessToken;
    pb_callback_t name;
    pb_callback_t items;
    double health;
} testprotos_PlayerResponse;

typedef struct _testprotos_BigMessageResponse { 
    bool has_player;
    testprotos_PlayerResponse player;
    pb_callback_t npcs;
    pb_callback_t chests;
} testprotos_BigMessageResponse;

typedef struct _testprotos_BigMessageResponse_NpcsEntry { 
    pb_callback_t key;
    bool has_value;
    testprotos_NPC value;
} testprotos_BigMessageResponse_NpcsEntry;

typedef struct _testprotos_BigMessage { 
    pb_callback_t code;
    bool has_response;
    testprotos_BigMessageResponse response;
} testprotos_BigMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define testprotos_PlayerResponse_init_default   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define testprotos_NPC_init_default              {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define testprotos_BigMessageResponse_init_default {false, testprotos_PlayerResponse_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define testprotos_BigMessageResponse_NpcsEntry_init_default {{{NULL}, NULL}, false, testprotos_NPC_init_default}
#define testprotos_BigMessage_init_default       {{{NULL}, NULL}, false, testprotos_BigMessageResponse_init_default}
#define testprotos_PlayerResponse_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define testprotos_NPC_init_zero                 {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define testprotos_BigMessageResponse_init_zero  {false, testprotos_PlayerResponse_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define testprotos_BigMessageResponse_NpcsEntry_init_zero {{{NULL}, NULL}, false, testprotos_NPC_init_zero}
#define testprotos_BigMessage_init_zero          {{{NULL}, NULL}, false, testprotos_BigMessageResponse_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define testprotos_NPC_name_tag                  1
#define testprotos_NPC_health_tag                2
#define testprotos_NPC_publicId_tag              3
#define testprotos_PlayerResponse_publicId_tag   1
#define testprotos_PlayerResponse_accessToken_tag 2
#define testprotos_PlayerResponse_name_tag       3
#define testprotos_PlayerResponse_items_tag      4
#define testprotos_PlayerResponse_health_tag     5
#define testprotos_BigMessageResponse_player_tag 1
#define testprotos_BigMessageResponse_npcs_tag   2
#define testprotos_BigMessageResponse_chests_tag 3
#define testprotos_BigMessageResponse_NpcsEntry_key_tag 1
#define testprotos_BigMessageResponse_NpcsEntry_value_tag 2
#define testprotos_BigMessage_code_tag           1
#define testprotos_BigMessage_response_tag       2

/* Struct field encoding specification for nanopb */
#define testprotos_PlayerResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   publicId,          1) \
X(a, CALLBACK, SINGULAR, STRING,   accessToken,       2) \
X(a, CALLBACK, SINGULAR, STRING,   name,              3) \
X(a, CALLBACK, REPEATED, STRING,   items,             4) \
X(a, STATIC,   SINGULAR, DOUBLE,   health,            5)
#define testprotos_PlayerResponse_CALLBACK pb_default_field_callback
#define testprotos_PlayerResponse_DEFAULT NULL

#define testprotos_NPC_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, DOUBLE,   health,            2) \
X(a, CALLBACK, SINGULAR, STRING,   publicId,          3)
#define testprotos_NPC_CALLBACK pb_default_field_callback
#define testprotos_NPC_DEFAULT NULL

#define testprotos_BigMessageResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  player,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  npcs,              2) \
X(a, CALLBACK, REPEATED, STRING,   chests,            3)
#define testprotos_BigMessageResponse_CALLBACK pb_default_field_callback
#define testprotos_BigMessageResponse_DEFAULT NULL
#define testprotos_BigMessageResponse_player_MSGTYPE testprotos_PlayerResponse
#define testprotos_BigMessageResponse_npcs_MSGTYPE testprotos_BigMessageResponse_NpcsEntry

#define testprotos_BigMessageResponse_NpcsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define testprotos_BigMessageResponse_NpcsEntry_CALLBACK pb_default_field_callback
#define testprotos_BigMessageResponse_NpcsEntry_DEFAULT NULL
#define testprotos_BigMessageResponse_NpcsEntry_value_MSGTYPE testprotos_NPC

#define testprotos_BigMessage_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   code,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  response,          2)
#define testprotos_BigMessage_CALLBACK pb_default_field_callback
#define testprotos_BigMessage_DEFAULT NULL
#define testprotos_BigMessage_response_MSGTYPE testprotos_BigMessageResponse

extern const pb_msgdesc_t testprotos_PlayerResponse_msg;
extern const pb_msgdesc_t testprotos_NPC_msg;
extern const pb_msgdesc_t testprotos_BigMessageResponse_msg;
extern const pb_msgdesc_t testprotos_BigMessageResponse_NpcsEntry_msg;
extern const pb_msgdesc_t testprotos_BigMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define testprotos_PlayerResponse_fields &testprotos_PlayerResponse_msg
#define testprotos_NPC_fields &testprotos_NPC_msg
#define testprotos_BigMessageResponse_fields &testprotos_BigMessageResponse_msg
#define testprotos_BigMessageResponse_NpcsEntry_fields &testprotos_BigMessageResponse_NpcsEntry_msg
#define testprotos_BigMessage_fields &testprotos_BigMessage_msg

/* Maximum encoded size of messages (where known) */
/* testprotos_PlayerResponse_size depends on runtime parameters */
/* testprotos_NPC_size depends on runtime parameters */
/* testprotos_BigMessageResponse_size depends on runtime parameters */
/* testprotos_BigMessageResponse_NpcsEntry_size depends on runtime parameters */
/* testprotos_BigMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
