/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Fri Jun 29 10:55:13 2018. */

#include "big-message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t protos_PlayerResponse_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_PlayerResponse, publicId, publicId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, protos_PlayerResponse, accessToken, publicId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, protos_PlayerResponse, name, accessToken, 0),
    PB_FIELD(  4, STRING  , REPEATED, CALLBACK, OTHER, protos_PlayerResponse, items, name, 0),
    PB_FIELD(  5, DOUBLE  , SINGULAR, STATIC  , OTHER, protos_PlayerResponse, health, items, 0),
    PB_LAST_FIELD
};

const pb_field_t protos_NPC_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_NPC, name, name, 0),
    PB_FIELD(  2, DOUBLE  , SINGULAR, STATIC  , OTHER, protos_NPC, health, name, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, protos_NPC, publicId, health, 0),
    PB_LAST_FIELD
};

const pb_field_t protos_BigMessageResponse_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, protos_BigMessageResponse, player, player, &protos_PlayerResponse_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, protos_BigMessageResponse, npcs, player, &protos_BigMessageResponse_NpcsEntry_fields),
    PB_FIELD(  3, STRING  , REPEATED, CALLBACK, OTHER, protos_BigMessageResponse, chests, npcs, 0),
    PB_LAST_FIELD
};

const pb_field_t protos_BigMessageResponse_NpcsEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_BigMessageResponse_NpcsEntry, key, key, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, protos_BigMessageResponse_NpcsEntry, value, key, &protos_NPC_fields),
    PB_LAST_FIELD
};

const pb_field_t protos_BigMessage_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_BigMessage, code, code, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, protos_BigMessage, response, code, &protos_BigMessageResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protos_BigMessageResponse, player) < 65536 && pb_membersize(protos_BigMessageResponse_NpcsEntry, value) < 65536 && pb_membersize(protos_BigMessage, response) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_protos_PlayerResponse_protos_NPC_protos_BigMessageResponse_protos_BigMessageResponse_NpcsEntry_protos_BigMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(protos_BigMessageResponse, player) < 256 && pb_membersize(protos_BigMessageResponse_NpcsEntry, value) < 256 && pb_membersize(protos_BigMessage, response) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_protos_PlayerResponse_protos_NPC_protos_BigMessageResponse_protos_BigMessageResponse_NpcsEntry_protos_BigMessage)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
