/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Fri Jun 29 10:55:13 2018. */

#ifndef PB_PROTOS_BIG_MESSAGE_PB_H_INCLUDED
#define PB_PROTOS_BIG_MESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_NPC {
    pb_callback_t name;
    double health;
    pb_callback_t publicId;
/* @@protoc_insertion_point(struct:protos_NPC) */
} protos_NPC;

typedef struct _protos_PlayerResponse {
    pb_callback_t publicId;
    pb_callback_t accessToken;
    pb_callback_t name;
    pb_callback_t items;
    double health;
/* @@protoc_insertion_point(struct:protos_PlayerResponse) */
} protos_PlayerResponse;

typedef struct _protos_BigMessageResponse {
    protos_PlayerResponse player;
    pb_callback_t npcs;
    pb_callback_t chests;
/* @@protoc_insertion_point(struct:protos_BigMessageResponse) */
} protos_BigMessageResponse;

typedef struct _protos_BigMessageResponse_NpcsEntry {
    pb_callback_t key;
    protos_NPC value;
/* @@protoc_insertion_point(struct:protos_BigMessageResponse_NpcsEntry) */
} protos_BigMessageResponse_NpcsEntry;

typedef struct _protos_BigMessage {
    pb_callback_t code;
    protos_BigMessageResponse response;
/* @@protoc_insertion_point(struct:protos_BigMessage) */
} protos_BigMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define protos_PlayerResponse_init_default       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protos_NPC_init_default                  {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protos_BigMessageResponse_init_default   {protos_PlayerResponse_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define protos_BigMessageResponse_NpcsEntry_init_default {{{NULL}, NULL}, protos_NPC_init_default}
#define protos_BigMessage_init_default           {{{NULL}, NULL}, protos_BigMessageResponse_init_default}
#define protos_PlayerResponse_init_zero          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define protos_NPC_init_zero                     {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define protos_BigMessageResponse_init_zero      {protos_PlayerResponse_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define protos_BigMessageResponse_NpcsEntry_init_zero {{{NULL}, NULL}, protos_NPC_init_zero}
#define protos_BigMessage_init_zero              {{{NULL}, NULL}, protos_BigMessageResponse_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define protos_NPC_name_tag                      1
#define protos_NPC_health_tag                    2
#define protos_NPC_publicId_tag                  3
#define protos_PlayerResponse_publicId_tag       1
#define protos_PlayerResponse_accessToken_tag    2
#define protos_PlayerResponse_name_tag           3
#define protos_PlayerResponse_items_tag          4
#define protos_PlayerResponse_health_tag         5
#define protos_BigMessageResponse_player_tag     1
#define protos_BigMessageResponse_npcs_tag       2
#define protos_BigMessageResponse_chests_tag     3
#define protos_BigMessageResponse_NpcsEntry_key_tag 1
#define protos_BigMessageResponse_NpcsEntry_value_tag 2
#define protos_BigMessage_code_tag               1
#define protos_BigMessage_response_tag           2

/* Struct field encoding specification for nanopb */
extern const pb_field_t protos_PlayerResponse_fields[6];
extern const pb_field_t protos_NPC_fields[4];
extern const pb_field_t protos_BigMessageResponse_fields[4];
extern const pb_field_t protos_BigMessageResponse_NpcsEntry_fields[3];
extern const pb_field_t protos_BigMessage_fields[3];

/* Maximum encoded size of messages (where known) */
/* protos_PlayerResponse_size depends on runtime parameters */
/* protos_NPC_size depends on runtime parameters */
/* protos_BigMessageResponse_size depends on runtime parameters */
/* protos_BigMessageResponse_NpcsEntry_size depends on runtime parameters */
/* protos_BigMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BIG_MESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
