/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "error.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protos_Error, protos_Error, AUTO)


PB_BIND(protos_Error_MetadataEntry, protos_Error_MetadataEntry, AUTO)



