/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Jun 27 11:48:04 2018. */

#include "error.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t protos_Error_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_Error, code, code, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, protos_Error, msg, code, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, protos_Error, metadata, msg, &protos_Error_MetadataEntry_fields),
    PB_LAST_FIELD
};

const pb_field_t protos_Error_MetadataEntry_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_Error_MetadataEntry, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, protos_Error_MetadataEntry, value, key, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
