/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Jun 27 18:15:31 2018. */

#ifndef PB_PROTOS_RESPONSE_PB_H_INCLUDED
#define PB_PROTOS_RESPONSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_Response {
    int32_t code;
    pb_callback_t msg;
/* @@protoc_insertion_point(struct:protos_Response) */
} protos_Response;

/* Default values for struct fields */

/* Initializer values for message structs */
#define protos_Response_init_default             {0, {{NULL}, NULL}}
#define protos_Response_init_zero                {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_Response_code_tag                 1
#define protos_Response_msg_tag                  2

/* Struct field encoding specification for nanopb */
extern const pb_field_t protos_Response_fields[3];

/* Maximum encoded size of messages (where known) */
/* protos_Response_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define RESPONSE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
