/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Jun 27 18:15:31 2018. */

#include "response.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t protos_Response_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, protos_Response, code, code, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, protos_Response, msg, code, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
