/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Wed Jun 27 17:17:10 2018. */

#include "session-data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t protos_SessionData_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, protos_SessionData, data, data, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
