/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_PROTOS_SESSION_DATA_PB_H_INCLUDED
#define PB_PROTOS_SESSION_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _protos_SessionData { 
    pb_callback_t data;
} protos_SessionData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define protos_SessionData_init_default          {{{NULL}, NULL}}
#define protos_SessionData_init_zero             {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_SessionData_data_tag              1

/* Struct field encoding specification for nanopb */
#define protos_SessionData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   data,              1)
#define protos_SessionData_CALLBACK pb_default_field_callback
#define protos_SessionData_DEFAULT NULL

extern const pb_msgdesc_t protos_SessionData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protos_SessionData_fields &protos_SessionData_msg

/* Maximum encoded size of messages (where known) */
/* protos_SessionData_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
