/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Wed Jun 27 17:17:10 2018. */

#ifndef PB_PROTOS_SESSION_DATA_PB_H_INCLUDED
#define PB_PROTOS_SESSION_DATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _protos_SessionData {
    pb_callback_t data;
/* @@protoc_insertion_point(struct:protos_SessionData) */
} protos_SessionData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define protos_SessionData_init_default          {{{NULL}, NULL}}
#define protos_SessionData_init_zero             {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protos_SessionData_data_tag              1

/* Struct field encoding specification for nanopb */
extern const pb_field_t protos_SessionData_fields[2];

/* Maximum encoded size of messages (where known) */
/* protos_SessionData_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SESSION_DATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
