// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.6
// source: big-message.proto

package testprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicId    string   `protobuf:"bytes,1,opt,name=publicId,proto3" json:"publicId,omitempty"`
	AccessToken string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	Name        string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Items       []string `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Health      float64  `protobuf:"fixed64,5,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_big_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_big_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_big_message_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerResponse) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *PlayerResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PlayerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerResponse) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlayerResponse) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

type NPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Health   float64 `protobuf:"fixed64,2,opt,name=health,proto3" json:"health,omitempty"`
	PublicId string  `protobuf:"bytes,3,opt,name=publicId,proto3" json:"publicId,omitempty"`
}

func (x *NPC) Reset() {
	*x = NPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_big_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPC) ProtoMessage() {}

func (x *NPC) ProtoReflect() protoreflect.Message {
	mi := &file_big_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPC.ProtoReflect.Descriptor instead.
func (*NPC) Descriptor() ([]byte, []int) {
	return file_big_message_proto_rawDescGZIP(), []int{1}
}

func (x *NPC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NPC) GetHealth() float64 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *NPC) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type BigMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *PlayerResponse `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Npcs   map[string]*NPC `protobuf:"bytes,2,rep,name=npcs,proto3" json:"npcs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Chests []string        `protobuf:"bytes,3,rep,name=chests,proto3" json:"chests,omitempty"`
}

func (x *BigMessageResponse) Reset() {
	*x = BigMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_big_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigMessageResponse) ProtoMessage() {}

func (x *BigMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_big_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigMessageResponse.ProtoReflect.Descriptor instead.
func (*BigMessageResponse) Descriptor() ([]byte, []int) {
	return file_big_message_proto_rawDescGZIP(), []int{2}
}

func (x *BigMessageResponse) GetPlayer() *PlayerResponse {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *BigMessageResponse) GetNpcs() map[string]*NPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *BigMessageResponse) GetChests() []string {
	if x != nil {
		return x.Chests
	}
	return nil
}

type BigMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     string              `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Response *BigMessageResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *BigMessage) Reset() {
	*x = BigMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_big_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigMessage) ProtoMessage() {}

func (x *BigMessage) ProtoReflect() protoreflect.Message {
	mi := &file_big_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigMessage.ProtoReflect.Descriptor instead.
func (*BigMessage) Descriptor() ([]byte, []int) {
	return file_big_message_proto_rawDescGZIP(), []int{3}
}

func (x *BigMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BigMessage) GetResponse() *BigMessageResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_big_message_proto protoreflect.FileDescriptor

var file_big_message_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x69, 0x67, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22,
	0x90, 0x01, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x22, 0x4d, 0x0a, 0x03, 0x4e, 0x50, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x64, 0x22, 0xe8, 0x01, 0x0a, 0x12, 0x42, 0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x04,
	0x6e, 0x70, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x70, 0x63, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6e, 0x70, 0x63, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x65, 0x73,
	0x74, 0x73, 0x1a, 0x48, 0x0a, 0x09, 0x4e, 0x70, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4e, 0x50,
	0x43, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a, 0x0a,
	0x42, 0x69, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x3a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x69,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x70, 0x66, 0x72, 0x65, 0x65,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x62, 0x70, 0x69, 0x74, 0x61, 0x79, 0x61, 0x2f,
	0x70, 0x69, 0x74, 0x61, 0x79, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_big_message_proto_rawDescOnce sync.Once
	file_big_message_proto_rawDescData = file_big_message_proto_rawDesc
)

func file_big_message_proto_rawDescGZIP() []byte {
	file_big_message_proto_rawDescOnce.Do(func() {
		file_big_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_big_message_proto_rawDescData)
	})
	return file_big_message_proto_rawDescData
}

var file_big_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_big_message_proto_goTypes = []interface{}{
	(*PlayerResponse)(nil),     // 0: testprotos.PlayerResponse
	(*NPC)(nil),                // 1: testprotos.NPC
	(*BigMessageResponse)(nil), // 2: testprotos.BigMessageResponse
	(*BigMessage)(nil),         // 3: testprotos.BigMessage
	nil,                        // 4: testprotos.BigMessageResponse.NpcsEntry
}
var file_big_message_proto_depIdxs = []int32{
	0, // 0: testprotos.BigMessageResponse.player:type_name -> testprotos.PlayerResponse
	4, // 1: testprotos.BigMessageResponse.npcs:type_name -> testprotos.BigMessageResponse.NpcsEntry
	2, // 2: testprotos.BigMessage.response:type_name -> testprotos.BigMessageResponse
	1, // 3: testprotos.BigMessageResponse.NpcsEntry.value:type_name -> testprotos.NPC
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_big_message_proto_init() }
func file_big_message_proto_init() {
	if File_big_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_big_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_big_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_big_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_big_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_big_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_big_message_proto_goTypes,
		DependencyIndexes: file_big_message_proto_depIdxs,
		MessageInfos:      file_big_message_proto_msgTypes,
	}.Build()
	File_big_message_proto = out.File
	file_big_message_proto_rawDesc = nil
	file_big_message_proto_goTypes = nil
	file_big_message_proto_depIdxs = nil
}
