platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'



abstract_target 'common' do
  pod 'Pitaya', path: '../../'
  target 'PitayaClient' do
  end
  target 'PitayaClientTests' do
      pod 'Protobuf'
  end
  
end
