// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: my.proto

// ReSharper disable All
#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace protos
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Error : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string code { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> metadata { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
