name: Build binaries

on:
  push:
    branches: '*'
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Build
        run: make build-ios


