name: Build binaries

on:
  push:
    branches: '*'
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Build
        run: make build-ios

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: libpitaya_ios
          path: |
            _builds/ios/Release-iphoneos/libpitaya-ios.a
            _builds/ios/deps/libuv-v1.44.2/Release-iphoneos/libuv_a.a

  build-mac:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: make build-mac-xcode

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: libpitaya_mac
          path: _builds/mac-xcode/libpitaya-mac.bundle

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt update && sudo apt install make cmake g++ git ninja-build python3 zlib1g-dev -y

      - name: Setup dependencies
        run: make setup-android-linux

      - name: Build
        run: make build-android

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: libpitaya_android
          path: _builds/android/libpitaya-android.so

  build-android-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages
        run: sudo apt update && sudo apt install make cmake g++ git ninja-build python3 zlib1g-dev -y

      - name: Setup dependencies
        run: make setup-android-linux

      - name: Build
        run: make build-android-64

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: libpitaya_android64
          path: _builds/android64/libpitaya-android.so
